name: Self Build and Test CI

on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      run: echo ::set-env name=TAG::$(echo ${GITHUB_SHA:0:7})
    - name: Use make build and test (via pytest)
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: make build_and_test
