name: Self Docker Image CD

on:
  release:
    types: [published]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build -t heyronhay/self:${{steps.vars.outputs.tag}} .
    - name: Tag the image with the git hash and latest
      run: docker tag heyronhay/self:${{steps.vars.outputs.tag}} heyronhay/self:latest
    - name: Push the tagged Docker image
      run: docker push heyronhay/self

